import React from "react";
import {
  PsychedelicSpiral,
  PerlinField,
  RandomWalk,
  Epicycloid,
  PerlinFlow,
  Cityscape,
  QuantumHarmonics,
} from "sketches";

export type Tags =
  | "Noise"
  | "Geometry"
  | "Particles"
  | "Animation"
  | "Interactive"
  | "Mathematical"
  | "Organic"
  | "Simulation"
  | "Fractals";

export type SketchItem = {
  name: string;
  slug: string;
  component: JSX.Element;
  description: string;
  tags?: Array<Tags>;
};

export const sketches: Array<SketchItem> = [
  {
    name: "Multiplicative Epicycloid",
    slug: "multiplicative-epicycloid",
    component: <Epicycloid />,
    description:
      "Mathematical curves generated by circles rolling around other circles.",
    tags: ["Geometry", "Mathematical", "Animation"],
  },
  {
    name: "Perlin Field",
    slug: "perlin-field",
    component: <PerlinField />,
    description:
      "Perlin noise, the algorithm behind natural-looking randomness.",
    tags: ["Noise", "Interactive"],
  },
  {
    name: "Perlin Flow",
    slug: "perlin-flow",
    component: <PerlinFlow />,
    description:
      "Particles flowing through a Perlin noise field, looks pretty cool.",
    tags: ["Noise", "Particles", "Simulation"],
  },
  {
    name: "Random Walk",
    slug: "random-walk",
    component: <RandomWalk />,
    description: "Particles move randomly step by step, that's it.",
    tags: ["Simulation", "Organic"],
  },
  {
    name: "Cityscape",
    slug: "cityscape",
    component: <Cityscape />,
    description:
      "Procedurally generated city skylines with adjustable building parameters.",
    tags: ["Geometry", "Interactive", "Simulation"],
  },
  {
    name: "Psychedelic Spiral",
    slug: "psychedelic-spiral",
    component: <PsychedelicSpiral />,
    description: "Rotating spiral with color-shifting particles",
    tags: ["Noise", "Particles", "Animation", "Fractals"],
  },
  {
    name: "Quantum Harmonics",
    slug: "quantum-harmonics",
    component: <QuantumHarmonics />,
    description: "Wave interference patterns from draggable sources.",
    tags: ["Mathematical", "Animation", "Interactive"],
  },
];
